#
# .gitlab-ci.yml - Copyright (c) 2001-2023 - Olivier Poncet
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# ----------------------------------------------------------------------------
# image
# ----------------------------------------------------------------------------

image: gcc

# ----------------------------------------------------------------------------
# stages
# ----------------------------------------------------------------------------

stages:
  - prepare
  - build

# ----------------------------------------------------------------------------
# tarball
# ----------------------------------------------------------------------------

tarball:
  stage: prepare
  tags:
    - debian-11
    - amd64
  script:
    - ./bin/ci-prepare.sh
    - ./bin/ci-build-all.sh
  artifacts:
    paths:
      - ./*.tar.gz

# ----------------------------------------------------------------------------
# debian-package-amd64
# ----------------------------------------------------------------------------

debian-package-amd64:
  stage: build
  tags:
    - debian-11
    - amd64
  dependencies:
    - tarball
  script:
    - ./bin/ci-build-deb.sh
  artifacts:
    paths:
      - ./*.deb

# ----------------------------------------------------------------------------
# debian-package-arm64
# ----------------------------------------------------------------------------

debian-package-arm64:
  stage: build
  tags:
    - debian-11
    - arm64
  dependencies:
    - tarball
  script:
    - ./bin/ci-build-deb.sh
  artifacts:
    paths:
      - ./*.deb

# ----------------------------------------------------------------------------
# End-Of-File
# ----------------------------------------------------------------------------
